/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tshirt.gltf 
Author: kylelhb (https://sketchfab.com/kylelhb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/oversized-t-shirt-3b6e78d6a1a74370a6e5af6f312d38f7
Title: Oversized t-shirt
*/

import React from 'react'
import { useGLTF } from '@react-three/drei';
import { BoxGeometry } from 'three';
import { Color } from 'three';

export default function Tshirt({ color, updateImgColor, ...props }) {
  const { nodes, materials } = useGLTF('/tshirt.gltf')
  materials['Material.001'].color = new Color(color);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={5.5}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} position={[0, 0, -1.5]}/>
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.001']} position={[0, 0, -1.5]}/>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} position={[0, 0, -1.5]}/>
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} position={[0, 0, -1.5]}/>
        <primitive object={new BoxGeometry(1, 1, 1)} />
      </group>
    </group>
  )
}

useGLTF.preload('/tshirt.gltf')
